name: Playwright Tests

on:
  push:
    branches:
      - main    # Trigger on push to main branch
  pull_request:
    branches:
      - main    # Trigger on pull request to main branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8080:8080

    steps:
    # Step 1: Checkout the repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Cache node_modules
    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        npm ci

    # Step 5: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t playwright-tests .

    # Step 6: Run the tests inside Docker
    - name: Run Playwright Tests
      run: |
        docker run --rm playwright-tests

    # Step 7: Upload Playwright Test results (Optional)
    - name: Upload Playwright test results
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report
